<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'LDAP Mapping' => '',
    '<strong>Create</strong> new ldap mapping' => '<strong>Utwórz</strong>  nowe mapowanie ldap',
    '<strong>Edit</strong> ldap mapping' => '<strong>Edytuj</strong> mapowanie ldap',
    '<strong>LDAP</strong> member mapping' => 'Mapowanie użytkowników <strong>LDAP</strong>',
    'Create new mapping' => 'Utwórz nowe mapowanie',
    'Group' => 'Grupa',
    'ID' => 'ID',
    'LDAP' => 'LDAP',
    'LDAP DN' => 'LDAP DN',
    'Space ID' => 'ID Strefy',
];
