<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'LDAP' => '',
    'LDAP DN' => '',
    'LDAP Mapping' => '',
    '<strong>Create</strong> new ldap mapping' => '<strong>Yeni</strong> ldap eşleme oluştur',
    '<strong>Edit</strong> ldap mapping' => '<strong>Düzenleme</strong> ldap haritalama',
    '<strong>LDAP</strong> member mapping' => '<strong>LDAP</strong> üye haritalama',
    'Create new mapping' => 'Yeni bir eşleme oluştur',
    'Group' => 'Grup',
    'ID' => 'İD',
    'Space ID' => 'Alan İD',
];
